// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tickNumber: __t.u32().name("tick_number"),
  entryType: __t.string().name("entry_type"),
  civColor: __t.string().name("civ_color"),
  godColor: __t.string().name("god_color"),
  text: __t.string(),
  relatedTerritoryId: __t.i32().name("related_territory_id"),
});
