// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  color: __t.string(),
  population: __t.i32(),
  techLevel: __t.i32().name("tech_level"),
  aggression: __t.i32(),
  piety: __t.i32(),
  mercantile: __t.i32(),
  scholarly: __t.i32(),
  stability: __t.i32(),
  leaderPersona: __t.string().name("leader_persona"),
  currentThought: __t.string().name("current_thought"),
  isAlive: __t.bool().name("is_alive"),
});
